"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";
import { authDestination } from "@/lib/auth-flow";

export default function SignInForm() {
  const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const [totp, setTotp] = useState(false);
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setLoading(true); setError(""); try { const form = new FormData(e.currentTarget); const response = await fetch(totp ? "/api/auth/totp" : "/api/auth/signin", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(totp ? { code: form.get("code") } : { email: form.get("email"), password: form.get("password") }) }); const data = await response.json().catch(() => ({})); if (!response.ok) { setError(data.error || "La connexion a échoué."); setLoading(false); return; } if (data.requiresTotp) { setTotp(true); setLoading(false); return; } const destination = authDestination(Boolean(data.onboardingRequired)); try { window.location.replace(destination); window.setTimeout(() => setLoading(false), 1_500); } catch { setError("La redirection a échoué. Réessayez."); setLoading(false); } } catch { setError("La connexion est temporairement indisponible. Réessayez."); setLoading(false); } }
  return <main className="auth-page"><section className="auth-card"><Link className="brand" href="/"><span>◒</span>shelf</Link><h1>Bon retour.</h1>{totp && <p>Saisissez votre code d’authentification.</p>}<form className="auth-form" onSubmit={submit}>{totp ? <label>Code à 6 chiffres ou code de récupération<input name="code" autoComplete="one-time-code" required /></label> : <><label>Email<input name="email" type="email" autoComplete="email" required /></label><label>Mot de passe<input name="password" type="password" autoComplete="current-password" required /></label></>}{error && <div className="form-error">{error}</div>}<button className="dark-button" disabled={loading}>{loading ? "Connexion…" : "Se connecter"}</button></form>{!totp && <p className="auth-switch"><Link href="/forgot-password">Mot de passe oublié ?</Link><br />Pas encore de compte ? <Link href="/signup">Créer mon espace</Link></p>}</section></main>;
}
