import { and, eq, isNull } from "drizzle-orm";
import { NextResponse } from "next/server";
import { cookies } from "next/headers";
import { db } from "@/db";
import { recoveryCodes, users } from "@/db/schema";
import { createSession, cookieName, pendingTotpCookieName, readPendingTotpChallenge } from "@/lib/auth";
import { checkRateLimit, requestIdentity } from "@/lib/rate-limit";
import { decryptTotp, hashRecoveryCode, verifyTotp } from "@/lib/security";
export async function POST(request: Request) { if (!db) return NextResponse.json({ error: "Database not connected" }, { status: 503 }); const challenge = await readPendingTotpChallenge((await cookies()).get(pendingTotpCookieName)?.value); const { code } = await request.json(); if (!challenge) return NextResponse.json({ error: "Your sign-in challenge expired." }, { status: 401 }); if (await checkRateLimit("totp-login", requestIdentity(request, challenge.email), 5)) return NextResponse.json({ error: "Too many attempts. Try later." }, { status: 429 }); const user = await db.query.users.findFirst({ where: eq(users.id, challenge.id) }); if (!user?.totpEnabled || !user.totpSecretEncrypted || (challenge.sessionVersion ?? 0) !== user.sessionVersion) return NextResponse.json({ error: "Invalid sign-in challenge." }, { status: 401 }); let valid = verifyTotp(decryptTotp(user.totpSecretEncrypted), String(code || "")); if (!valid) { const recovery = await db.update(recoveryCodes).set({ usedAt:new Date() }).where(and(eq(recoveryCodes.userId,user.id),eq(recoveryCodes.codeHash,hashRecoveryCode(String(code || ""))),isNull(recoveryCodes.usedAt))).returning({ id:recoveryCodes.id }); valid = recovery.length > 0; } if (!valid) return NextResponse.json({ error: "Invalid authentication code." }, { status: 401 }); const response = NextResponse.json({ user: { id: user.id, name: user.name, email: user.email }, onboardingRequired: !user.emailVerifiedAt || !user.onboardingCompletedAt }); response.cookies.set(cookieName, await createSession({ id: user.id, name: user.name, email: user.email, sessionVersion: user.sessionVersion }), { httpOnly: true, secure: process.env.NODE_ENV === "production", sameSite: "lax", path: "/", maxAge: 60 * 60 * 24 * 30 }); response.cookies.set(pendingTotpCookieName, "", { httpOnly: true, path: "/", maxAge: 0 }); return response; }
