"use client";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { AccountSettings } from "@/app/components/account-settings";
import { request } from "@/lib/client";
type Account = { name: string | null; email: string; emailVerified: boolean; totpEnabled: boolean };
export function Onboarding() { const router = useRouter(); const [account, setAccount] = useState<Account | null>(null); const [notice, setNotice] = useState(""); const [error, setError] = useState(""); const [settings, setSettings] = useState(false); const [busy, setBusy] = useState(false);
  const load = () => request("/api/account").then(data => setAccount(data.user)).catch(() => setError("Impossible de charger les informations du compte."));
  useEffect(() => { void load(); const refresh = () => void load(); window.addEventListener("focus", refresh); const timer = window.setInterval(refresh, 5_000); return () => { window.removeEventListener("focus", refresh); window.clearInterval(timer); }; }, []);
  async function resend() { setBusy(true); setError(""); try { const data = await request("/api/account/resend-verification", { method: "POST" }); setNotice(data.sent ? "E-mail de vérification envoyé." : "La livraison est temporairement indisponible. Vous pourrez réessayer plus tard."); } catch (e) { setError((e as Error).message || "Veuillez patienter avant une nouvelle demande."); } finally { setBusy(false); } }
  async function finish() { if (!account?.emailVerified) return setError("La vérification de votre e-mail est nécessaire pour continuer."); setBusy(true); try { await request("/api/account/onboarding", { method: "POST" }); router.replace("/"); router.refresh(); } catch (e) { setError((e as Error).message || "Impossible de terminer cette étape."); setBusy(false); } }
  return <main className="auth-page"><section className="onboarding-card"><span className="brand"><span>◒</span>shelf</span><p className="eyebrow">COMPTE CRÉÉ ✓</p><h1>{account?.emailVerified ? "Sécurisez votre compte" : "Vérifiez votre adresse e-mail"}</h1>{!account ? <p>Chargement…</p> : !account.emailVerified ? <><p>Nous avons envoyé un lien de vérification à <b>{account.email}</b>. Ouvrez-le pour continuer.</p><p>Si vous ne voyez pas l’e-mail après quelques minutes, vérifiez votre dossier spam ou courrier indésirable.</p><button className="outline-button" disabled={busy} onClick={() => void resend()}>{busy ? "Envoi…" : "Renvoyer l’e-mail"}</button></> : <><p>Ajoutez une application d’authentification pour protéger davantage votre compte. C’est facultatif.</p><section className="onboarding-step"><div><h2>Double authentification</h2><b>{account.totpEnabled ? "✓ Activée" : "Recommandée, mais facultative"}</b></div>{!account.totpEnabled && <button className="outline-button" onClick={() => setSettings(true)}>Configurer maintenant</button>}</section></>}{notice && <p className="settings-success" role="status">{notice}</p>}{error && <p className="form-error" role="alert">{error}</p>}{account?.emailVerified && <div className="onboarding-actions"><button className="dark-button" disabled={busy} onClick={() => void finish()}>Continuer vers Shelf</button><button className="quiet-button" disabled={busy} onClick={() => void finish()}>Continuer sans 2FA</button></div>}</section>{settings && <AccountSettings onClose={() => { setSettings(false); void load(); }} onSignOut={() => router.replace("/signin")} />}</main>; }
