"use client";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { AccountSettings } from "@/app/components/account-settings";
import { request } from "@/lib/client";
type Account = { name: string | null; email: string; emailVerified: boolean; totpEnabled: boolean };
export function Onboarding() { const router = useRouter(); const [account, setAccount] = useState<Account | null>(null); const [notice, setNotice] = useState(""); const [error, setError] = useState(""); const [settings, setSettings] = useState(false); const [busy, setBusy] = useState(false);
  const load = () => request("/api/account").then(data => setAccount(data.user)).catch(() => setError("Impossible de charger les informations du compte."));
  useEffect(() => { void load(); }, []);
  async function resend() { setBusy(true); setError(""); try { const data = await request("/api/account/resend-verification", { method: "POST" }); setNotice(data.sent ? "E-mail de vérification envoyé." : "La livraison est temporairement indisponible. Vous pourrez réessayer plus tard."); } catch (e) { setError((e as Error).message || "Veuillez patienter avant une nouvelle demande."); } finally { setBusy(false); } }
  async function finish() { setBusy(true); try { await request("/api/account/onboarding", { method: "POST" }); router.replace("/"); router.refresh(); } catch (e) { setError((e as Error).message || "Impossible de terminer cette étape."); setBusy(false); } }
  return <main className="auth-page"><section className="onboarding-card"><span className="brand"><span>◒</span>shelf</span><p className="eyebrow">COMPTE CRÉÉ ✓</p><h1>Bienvenue{account?.name ? `, ${account.name}` : ""}.</h1><p>Votre espace est prêt. Ces protections restent facultatives.</p>{!account ? <p>Chargement…</p> : <><section className="onboarding-step"><div><h2>1. Vérifier votre e-mail</h2><p>{account.email}</p><b className={account.emailVerified ? "security-good" : "security-pending"}>{account.emailVerified ? "✓ E-mail vérifié" : "En attente de vérification"}</b></div>{!account.emailVerified && <button className="outline-button" disabled={busy} onClick={() => void resend()}>{busy ? "Envoi…" : "Renvoyer l’e-mail"}</button>}</section><section className="onboarding-step"><div><h2>2. Protéger votre compte</h2><p>Utilisez une application d’authentification pour plus de sécurité.</p><b>{account.totpEnabled ? "✓ Double authentification activée" : "Recommandée, mais facultative"}</b></div>{!account.totpEnabled && <button className="outline-button" onClick={() => setSettings(true)}>Configurer</button>}</section></>}{notice && <p className="settings-success" role="status">{notice}</p>}{error && <p className="form-error" role="alert">{error}</p>}<div className="onboarding-actions"><button className="dark-button" disabled={busy} onClick={() => void finish()}>Continuer vers Shelf</button><button className="quiet-button" disabled={busy} onClick={() => void finish()}>Peut-être plus tard</button></div></section>{settings && <AccountSettings onClose={() => { setSettings(false); void load(); }} onSignOut={() => router.replace("/signin")} />}</main>; }
