import { boolean, index, integer, pgTable, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";

export const users = pgTable("users", { id: uuid("id").defaultRandom().primaryKey(), email: text("email").notNull().unique(), name: text("name"), passwordHash: text("password_hash").notNull(), emailVerifiedAt: timestamp("email_verified_at", { withTimezone: true }), totpEnabled: boolean("totp_enabled").notNull().default(false), totpSecretEncrypted: text("totp_secret_encrypted"), sessionVersion: integer("session_version").notNull().default(0), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() });
export const emailVerificationTokens = pgTable("email_verification_tokens", { id: uuid("id").defaultRandom().primaryKey(), userId: uuid("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(), tokenHash: text("token_hash").notNull().unique(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), usedAt: timestamp("used_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [index("email_verification_tokens_user_idx").on(t.userId)]);
export const passwordResetTokens = pgTable("password_reset_tokens", { id: uuid("id").defaultRandom().primaryKey(), userId: uuid("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(), tokenHash: text("token_hash").notNull().unique(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), usedAt: timestamp("used_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [index("password_reset_tokens_user_idx").on(t.userId)]);
export const recoveryCodes = pgTable("recovery_codes", { id: uuid("id").defaultRandom().primaryKey(), userId: uuid("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(), codeHash: text("code_hash").notNull().unique(), usedAt: timestamp("used_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [index("recovery_codes_user_idx").on(t.userId)]);
export const authRateLimits = pgTable("auth_rate_limits", { key: text("key").primaryKey(), count: integer("count").notNull().default(0), windowStartedAt: timestamp("window_started_at", { withTimezone: true }).defaultNow().notNull() });
export const sources = pgTable("sources", { id: uuid("id").defaultRandom().primaryKey(), userId: uuid("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(), name: text("name").notNull(), feedUrl: text("feed_url").notNull(), siteUrl: text("site_url"), kind: text("kind").notNull().default("rss"), contentType: text("content_type").notNull().default("article"), category: text("category").notNull().default("Unsorted"), active: boolean("active").notNull().default(true), lastSyncedAt: timestamp("last_synced_at", { withTimezone: true }), lastSyncError: text("last_sync_error"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [index("sources_user_id_idx").on(t.userId), uniqueIndex("sources_user_feed_unique").on(t.userId, t.feedUrl)]);
export const items = pgTable("items", { id: uuid("id").defaultRandom().primaryKey(), sourceId: uuid("source_id").references(() => sources.id, { onDelete: "cascade" }).notNull(), guid: text("guid").notNull(), title: text("title").notNull(), url: text("url").notNull(), summary: text("summary"), author: text("author"), mediaType: text("media_type").notNull().default("article"), duration: text("duration"), imageUrl: text("image_url"), publishedAt: timestamp("published_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [index("items_source_published_idx").on(t.sourceId, t.publishedAt), uniqueIndex("items_source_guid_unique").on(t.sourceId, t.guid)]);
export const itemStates = pgTable("item_states", { id: uuid("id").defaultRandom().primaryKey(), userId: uuid("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(), itemId: uuid("item_id").references(() => items.id, { onDelete: "cascade" }).notNull(), saved: boolean("saved").notNull().default(false), read: boolean("read").notNull().default(false), readLater: boolean("read_later").notNull().default(false), progressSeconds: integer("progress_seconds").notNull().default(0), durationSeconds: integer("duration_seconds"), lastPlayedAt: timestamp("last_played_at", { withTimezone: true }), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [index("item_states_user_id_idx").on(t.userId)]);
