import { NextResponse } from "next/server";
import { cookies } from "next/headers";
import { db } from "@/db";
import { users } from "@/db/schema";
import { and, eq, isNull } from "drizzle-orm";
import { compare } from "bcryptjs";
import { cookieName, readSession } from "@/lib/auth";
import { pendingTotpCookieName } from "@/lib/auth";
import { checkRateLimit } from "@/lib/rate-limit";
import { decryptTotp, hashRecoveryCode, verifyTotp } from "@/lib/security";
export async function GET() { const session = await readSession((await cookies()).get(cookieName)?.value); if (!session || !db) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const user = await db.query.users.findFirst({ where: eq(users.id, session.id) }); if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); return NextResponse.json({ user: { id: user.id, email: user.email, name: user.name, emailVerified: Boolean(user.emailVerifiedAt), totpEnabled: user.totpEnabled, onboardingCompleted: Boolean(user.onboardingCompletedAt) } }); }
export async function DELETE(request: Request) { const session = await readSession((await cookies()).get(cookieName)?.value); if (!session || !db) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); if (await checkRateLimit("account-delete", session.id, 5, 60 * 60_000)) return NextResponse.json({ error: "Too many attempts. Try later." }, { status: 429 }); const { currentPassword, code, confirmation } = await request.json(); if (confirmation !== "SUPPRIMER") return NextResponse.json({ error: "Type SUPPRIMER to confirm." }, { status: 400 }); const user = await db.query.users.findFirst({ where: eq(users.id, session.id) }); if (!user || !(await compare(currentPassword || "", user.passwordHash))) return NextResponse.json({ error: "Current password is incorrect." }, { status: 400 }); if (user.totpEnabled) { const value = String(code || ""); const totpValid = user.totpSecretEncrypted && verifyTotp(decryptTotp(user.totpSecretEncrypted), value); if (!totpValid) { const { recoveryCodes } = await import("@/db/schema"); const consumed = await db.update(recoveryCodes).set({ usedAt: new Date() }).where(and(eq(recoveryCodes.userId, user.id), eq(recoveryCodes.codeHash, hashRecoveryCode(value)), isNull(recoveryCodes.usedAt))).returning({ id: recoveryCodes.id }); if (!consumed.length) return NextResponse.json({ error: "Valid TOTP or recovery code required." }, { status: 400 }); } } await db.delete(users).where(eq(users.id, user.id)); const response = NextResponse.json({ deleted: true }); response.cookies.set(cookieName, "", { httpOnly: true, secure: process.env.NODE_ENV === "production", sameSite: "lax", path: "/", maxAge: 0 }); response.cookies.set(pendingTotpCookieName, "", { httpOnly: true, secure: process.env.NODE_ENV === "production", sameSite: "lax", path: "/", maxAge: 0 }); return response; }
