"use client";
/* eslint-disable @next/next/no-img-element */
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
type User={id:string;email:string;name:string|null}; type Source={id:string;name:string;feedUrl:string;siteUrl:string|null}; type Video={id:string;title:string;url:string;imageUrl:string|null;publishedAt:string|null;sourceName:string}; type Preview={name:string;channelId:string};
export default function Home(){
 const[user,setUser]=useState<User|null|undefined>(undefined),[sources,setSources]=useState<Source[]>([]),[videos,setVideos]=useState<Video[]>([]),[open,setOpen]=useState(false),[error,setError]=useState(""),[saving,setSaving]=useState(false),[channel,setChannel]=useState(""),[preview,setPreview]=useState<Preview|null>(null),[checking,setChecking]=useState(false),[refreshing,setRefreshing]=useState(false);
 async function load(){const[s,v]=await Promise.all([fetch("/api/sources").then(r=>r.json()),fetch("/api/videos").then(r=>r.json())]);setSources(s.sources||[]);setVideos(v.videos||[])}
 useEffect(()=>{fetch("/api/auth/me").then(r=>r.json()).then(async({user})=>{if(user)await load();setUser(user)}).catch(()=>setUser(null))},[]);
 useEffect(()=>{if(!open||channel.trim().length<3)return;const t=setTimeout(async()=>{setChecking(true);const r=await fetch(`/api/youtube/resolve?input=${encodeURIComponent(channel)}`),d=await r.json().catch(()=>({}));setPreview(r.ok?d:null);setChecking(false)},600);return()=>clearTimeout(t)},[channel,open]);
 async function signOut(){await fetch("/api/auth/signout",{method:"POST"});setUser(null);setSources([]);setVideos([])}
 async function addChannel(e:FormEvent){e.preventDefault();setSaving(true);setError("");const r=await fetch("/api/sources",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({feedUrl:channel,kind:"youtube",category:"Vidéos"})}),d=await r.json().catch(()=>({}));if(!r.ok){setError(d.error||"Impossible d’ajouter la chaîne.");setSaving(false);return}await load();setSaving(false);setOpen(false);setChannel("");setPreview(null)}
 async function remove(id:string){if(!confirm("Supprimer cette chaîne et ses vidéos ?"))return;await fetch(`/api/sources/${id}`,{method:"DELETE"});await load()}
 async function refresh(){setRefreshing(true);await Promise.all(sources.map(s=>fetch(`/api/sources/${s.id}/sync`,{method:"POST"})));await load();setRefreshing(false)}
 if(user===undefined)return <main className="loading">Chargement…</main>;
 if(!user)return <main className="login-home"><Link href="/" className="brand"><span>◒</span>shelf</Link><section><h1>Vos chaînes.<br/>Votre rythme.</h1><p>Un lecteur simple pour les vidéos que vous choisissez.</p><div><Link href="/signup" className="dark-button">Créer un compte</Link><Link href="/signin" className="quiet-button">Se connecter</Link></div></section></main>;
 return <main className="dashboard"><aside className="side"><Link href="/" className="brand"><span>◒</span>shelf</Link><button className="add-source" onClick={()=>setOpen(true)}>＋ Ajouter une chaîne</button><nav className="main-nav"><button className="nav-active">◷ Boîte de réception <small>{videos.length}</small></button><button>♡ Enregistrés</button><button>✓ Lus</button></nav><p className="side-label">CHAÎNES</p><nav className="channel-nav">{sources.length?sources.map(s=><div key={s.id}><a href={s.siteUrl||s.feedUrl} target="_blank" rel="noreferrer"><span>{s.name[0].toUpperCase()}</span>{s.name}</a><button title="Supprimer" onClick={()=>remove(s.id)}>×</button></div>):<p>Aucune chaîne</p>}</nav><div className="account"><span>{(user.name||user.email)[0].toUpperCase()}</span><div><b>{user.name||user.email.split("@")[0]}</b><button onClick={signOut}>Se déconnecter</button></div></div></aside><section className="dashboard-content"><header><div><h1>Vidéos récentes</h1><p>{videos.length} vidéo{videos.length!==1?"s":""}</p></div><button className="outline-button" disabled={refreshing} onClick={refresh}>{refreshing?"Actualisation…":"Actualiser"}</button></header>{videos.length?<div className="video-grid">{videos.map(v=><article className="video-card" key={v.id}><a href={v.url} target="_blank" rel="noreferrer" className="video-thumb">{v.imageUrl?<img src={v.imageUrl} alt=""/>:<span>▶</span>}</a><p>{v.sourceName}</p><h2><a href={v.url} target="_blank" rel="noreferrer">{v.title}</a></h2><time>{v.publishedAt?new Intl.DateTimeFormat("fr-BE",{dateStyle:"medium"}).format(new Date(v.publishedAt)):""}</time></article>)}</div>:<div className="dashboard-empty"><span>▶</span><h2>Aucune vidéo</h2><p>Ajoute une chaîne YouTube. Ses dernières vidéos apparaîtront ici.</p><button className="dark-button" onClick={()=>setOpen(true)}>Ajouter une chaîne</button></div>}</section>{open&&<div className="modal-wrap" role="dialog" aria-modal="true"><form className="modal source-form" onSubmit={addChannel}><button className="close" type="button" onClick={()=>setOpen(false)}>×</button><h2>Ajouter une chaîne</h2><p>Colle une URL YouTube ou un handle. Le flux est trouvé automatiquement.</p><label>Chaîne YouTube<input value={channel} onChange={e=>{setChannel(e.target.value);setPreview(null)}} placeholder="@veritasium ou youtube.com/@veritasium" required autoFocus/></label>{checking&&<p className="lookup">Recherche de la chaîne…</p>}{preview&&<div className="channel-preview"><span>{preview.name?.[0]?.toUpperCase()||"▶"}</span><div><b>{preview.name}</b><small>Chaîne trouvée · flux RSS prêt</small></div></div>}{error&&<p className="form-error">{error}</p>}<button className="dark-button" disabled={saving||!preview}>{saving?"Ajout…":"Ajouter la chaîne"}</button></form></div>}</main>
}
